### ISSUE TITLE
Doesn't work with secondary drives.

### ISSUE THREAD

**Issue by Kneesnap** [eneam/mboxviewer#10]
I had a file on F:\file.mbox, and I could not for the life of me get it to show up. As soon as I moved it to C:\, mboxview was able to find it when I selected the folder. It was in the root directory. I didn't test whether or not putting it in a folder made a difference.

**Comment by zigm** [comment]
Hi,

You need to create a folder under F: drive and move the mbox file to that
folder, for example:

    F:\Mails\file.mbox.

Let me know if that works for you.

Thanks,
Zbigniew

**Comment by zigm** [comment]
Secondary drives are already supported but mbox files must be placed under user created folder and not under the root folder.
Enhanced code to validate folder path and released mew v1.0.3.13.
