### ISSUE TITLE
Trouble with indexing huge mbox file

### ISSUE THREAD

**Issue by Leberkassemml** [eneam/mboxviewer#11]
I am trying to open a 107GB mbox file. The parsing process seems to work, it finishes without errors and i am able to display and search through all mails. But the mboxview file doesn't get created next to the mbox file. Thus having to pars the file again once i close and reopen the program. Which takes quite a while.

Also when i try to refresh the index file without restarting the program first, an error message pops up: "Could not finish parsing due to memory fragmentation. Please restart the mbox viewer to resolve."

Is the mboxview file while being created, stored in a temporary folder where i can just copy it?

By the way, the biggest file i imported is 70GB and works fine.

**Comment by zigm** [comment]
Hi,

Issues you reported are unacceptable and need to be fixed. I merged
multiple mbox files to create large mbox files of size 110Gb and I was able
to recreate the reported issue. Unfortunately there is no work around this
bug running the latest version.

I am working on the new release to export all mail attachments and to
export all mails as eml files. I will resolve the reported issue in this
new release, hopefully soon.

The other issue, memory fragmentation issue, I did observe the issue in my
setup on rare occasions. Mbox viewer leverages the memory mapped Windows
features to boost parsing performance. I did research the issue on the
Internet but didn't find a solution or good explanation. Possible solution
is to rely on the standard file read facility which I will explore whether
impact on performance is acceptable.

Let you know when the new release is available.

Thanks for reporting the issue.
Zbigniew




I will investigate and hopefully release fix in the next release (work in
progress) of the mbox viewer

**Comment by Leberkassemml** [comment]
Thats good news. Thanks for looking into it.
The memory fragmentation is not a big issue, as it resolves itself by restarting. I just thought it might be connected to the indexing problem.

**Comment by zigm** [comment]
Hi,

Created new release v1.0.3.14 that resolves issue you reported and also supports number of other features.

Hope you find time to verify the fix and provide feedback.

Zbigniew

**Comment by Leberkassemml** [comment]
Just tried it with my 107GB file and it worked!
Thanks for your effort. I close this issue.
