### ISSUE TITLE
How to read a complete Thunderbirds export

### ISSUE THREAD

**Issue by kintaro1981** [eneam/mboxviewer#15]
Hello,
I exported a Thunderbird account but mboxview don't read it.
What I need to do to read the all dirs and sub-dirs?

I noticed that if I add .mbox to file names they are recognized but I can't see sub-dirs.

Regards

**Comment by zigm** [comment]
Hi,

The feature summary says that Thunderbird mails are supported. The mbox viewer can support eml messages which are believe was the mail format used by Thunderbird long time ago when the project was created by the original developer.  Mbox Viewer still supports mails in emal format. Thunderbird documentation seems to says now that Thunderbird uses mails in the mbox format. The eml and mbox mail formats are almost identical.

I don't have Thunderbird  account and didn't do any testing with the Thunderbird. I might be able to resolve the issue with your help.  I have a couple of questions:
1.  How did you export your account? Are different export options available to users?
2.  How many files were created by the export. My limited understanding  is that Thunderbird  creates a separate file per mail.
3. What are the names of the exported file(s)? Sounds you had to rename the exported files to mbox extension.
4. You stated that mbox viewer recognized the rename file(s). Does it mean that Mbox Viewer was able to parse the files. load and show the content?

Regards,
Zbigniew

**Comment by MikiGrit** [comment]
I've encountered the same issue. When exported from Thunderbird (with extension "ImportExportTools NG"). One have to add to each file extension ".mbox", then the files are properly read. It does not work for files in subfolder (wich is created with ".sbd" extension).

**Comment by zigm** [comment]
Thanks for raising the issue.  In order to minimize startup time, current Mbox Viewer will only validate files with .mbox and .eml file extensions. In reality, validation of all files will increase the startup time  only if a user select incorrect folder with very large number of non-mbox files. In order to validate whether a file is valid mail file, MBox Viewer needs to read and process first N characters from the file. 

Probably not a big harm to validate all files in a selected folder. There are a couple places MBox Viewer relies on .mbox and .eml file extensions such as merging mbox files.  I will investigate how many places would need to be enhanced not to rely on file extensions. Another option would be for Mbox Viewer to ask user for permission to add mbox file extension to files after validation. It is a bit surprising the Thunderbird doesn't export files with proper file extensions when exporting folder(s) as the mbox file(s).

I installed Thunderbird and created account to yahoo mail. Unfortunately sub-folders don't seem to be supported by the yahoo mail so I could not test exporting of sub-folders.

What Thunderbird account you have, to gmail? With gmail, you may need to export All Mails folder to be sure you downloaded all mails. However, with Gmail , you would likely rely on gmail export capability and not on the Thunderbird export capability.

Regards,
Zbigniew

**Comment by zigm** [comment]
In my case I don't have .sbd subfolders, only the below folders. They house the mbox files such as Inbox and .msf index files.

C:\Users\tata\AppData\Roaming\Thunderbird\Profiles\yng752b7.default-release\ImapMail\imap.mail.yahoo.com
C:\Users\tata\AppData\Roaming\Thunderbird\Profiles\yng752b7.default-release\Mail\Local Folders

From Internet:

SBD files are subdirectory files containing MBOX file and MSF file in it. To open an SBD file, one just need to import SBD to Thunderbird with MBOX which contains MBOX only. MSF files are index files so it is not necessary to import MSF to Thunderbird.

Are able to export SBD folders, rename exported files as MBOX files and open in MBox Viewer? If export is not supported fo SDB subfolders, it looks like you can open the above IMAP folder and copy the relevant files to the target folder.

For my benefit, can you show me path and content of .sbd folders?

**Comment by MikiGrit** [comment]
Thanks for fast responses,

regarding the account, I wanted to backup my old school account. So it was custom domain mail accessed through IMAP.

Here is list of the files. There were actually no other files than the ones without any extension (I went ahead and added the ".mbox" to all):
```
krupimik_fit_cvut_cz\cig.mbox
krupimik_fit_cvut_cz\doktorand.mbox
krupimik_fit_cvut_cz\Doručená pošta.mbox
krupimik_fit_cvut_cz\hromadne-fit.mbox
krupimik_fit_cvut_cz\konference.mbox
krupimik_fit_cvut_cz\Koš.mbox
krupimik_fit_cvut_cz\kti.mbox
krupimik_fit_cvut_cz\maillists.mbox
krupimik_fit_cvut_cz\Odeslaná pošta.mbox
krupimik_fit_cvut_cz\osobní.mbox
krupimik_fit_cvut_cz\různé.mbox
krupimik_fit_cvut_cz\spam.mbox
krupimik_fit_cvut_cz\utia.mbox
krupimik_fit_cvut_cz\vedení, oponentury.mbox
krupimik_fit_cvut_cz\teaching.sbd\bi-pa1.mbox
krupimik_fit_cvut_cz\teaching.sbd\bi-pa2.mbox
krupimik_fit_cvut_cz\teaching.sbd\bi-zum.mbox
krupimik_fit_cvut_cz\teaching.sbd\mi-roz.mbox
```

**Comment by zigm** [comment]
Thanks. Unfortunately as you indicated you had to add the .mbox extension to all listed files. You should be able to select two folders/containers to load all mbox files, i.e.  "krupimik_fit_cvut_cz"  and "teaching.sbd". I don't see "teaching.mbox" file which tells me that "teaching" was just a folder for sub-folders and no mails.  MBox Viewer doesn't automatically import all mbox files based on the root folder, i.e. "krupimik_fit_cvut_cz".

I did prototype ability to discover all sub-folders and mbox files based on the root directory but the feature is not completed and was not released. I may revisit what is missing and consider to release.

Let me know if you have any issues viewing the mbox files or any other feature.

Thank You

**Comment by MikiGrit** [comment]
Ok, thanks! 👍 The mbox files themselves load without any issues.

**Comment by zigm** [comment]
I wanted to let you know that I released v1.0.3.27 to support exports from Thunderbird as you requested I believe.

The new MBox Viewer will merge all mbox files under root folder and sub-folders and automatically recreate folder structure as Gmail style labels. 

Select "File-->Select root folder for merging.." option to automatically import all files based on the root folder.

I know old version sort of worked for you after you appended .mbox extensions to files.  Appending extension is no longer required in this release. If you decide to try the latest version, let me know if it worked for you and suggest enhancements if needed.

Note that this version of MBox Viewer will delete all files generated by currently installed MBox Viewer except for index files. During startup MBox Viewer will ask you whether it is ok to proceed. You may select NO if you wish to examine current files created by "Print To" or exports and save some if needed.

MBox Viewer will also ask you to configure data folder for all files created by new MBox Viewer.

README file lists all new features and changes implemented in v1.0.3.27.

**Comment by kintaro1981** [comment]
Thank you!
I'm going to test it in a couple of days.

**Comment by zigm** [comment]
This request is similar to closed ticket "   Feature request - Folder Depth #14 ".
