### ISSUE TITLE
Missing guide on*.mbox

### ISSUE THREAD

**Issue by czechdude** [eneam/mboxviewer#16]
Hi, I do not understand the program,
it does not offer an option to open my Gmail exported *.mbox file.

Thanks for help

**Comment by zigm** [comment]
UserGuide.pdf  is part of the package and describes all features. However, to Open the mbox file:

- download and unzip the latest mbox-viewer.exe-v1.0.3.18.zip file
- double left click on the mboxview.exe file
- On the left top of the mboxview main window, either select File --> Select Folder with the mbox file installed, or
- On the left top left click on the folder icon and select folder with the mbox file installed

Hope above helps. Let me know if that worked for you.

**Comment by czechdude** [comment]
Thanks!
It could not read the mbox file in the folder, maybe it was because crazy international characters and spaces created by Google. So I renamed it to english characters and now it works as you write!

**Comment by zigm** [comment]
The Mbox Viewer is not fully UNICODE. It supports UNICODE file names in most cases but may not the mbox file names. Thanks for letting me know.
