### ISSUE TITLE
is it portable?

### ISSUE THREAD

**Issue by kintaro1981** [eneam/mboxviewer#18]
Hello, 

I saw that some configurations (mbox paths) are wrote in the registry.
Can this be a problem in case of using it as "portable" app?

**Comment by zigm** [comment]
Hi,

The processPath is currently not used. It is set upon startup and set to empty upon shutdown.

Upon startup of the mboxview, I attempted to warn user that the mboxview process is already running. The solution was incomplete and the code was commented out. May revisit the solution in the future.

Thank you,
Zbigniew
