### ISSUE TITLE
Can I use it in my workplace?

### ISSUE THREAD

**Issue by vvclin-git** [eneam/mboxviewer#2]
Dear Sirs,

I wonder if I can use mboxviewer in my office; what is the license of this repository??

Thank you very much.

Wayne

**Comment by zigm** [comment]
Hi Wayne,

Mbox viewer source code is licensed under GPLv2 which means it is free to
use by anybody. The mbox viewer executable doesn't link any non-free to use
external code and is also free to use in any environment including office.

The mbox viewer is also distributed under Sourceforge site. The license
term is stated on the Summary page under Sourceforge site but not under
Github. I will add license terms on Github in the next release.

Regards,
Zbigniew

**Comment by zigm** [comment]
Closing the ticket.
