### ISSUE TITLE
Is ctrl+c disabled here? If so,why,is that a feature?

### ISSUE THREAD

**Issue by RedemptionC** [eneam/mboxviewer#20]
It seems I can only copy via right click menu

**Comment by zigm** [comment]
You are right that Copy is supported via the right click menu currently. Ctrl-C was not disabled but requires special code to support Ctrl-C.  MBox Viewer relies on standard Microsoft Web Browser object to display emails converted to HTML format.  Basic Web Browser doesn't support Ctrl-C. I did prototype code to support Ctrl-C and it seems to work.  I am working on few enhancements now but I will consider to release just this enhancement.  Let you know if I release Copy enhancement only and possibly some other low risk changes.
Thank you,
Zbigniew

**Comment by RedemptionC** [comment]
@zigm Thank you for your quick reply and explanation!
I think adding Ctrl-c will make someone's(at least me) workflow smoother,so,looking forward to your enhancemant :)

**Comment by zigm** [comment]
Created new MBox Viewer release  1.0.3.25 to support Ctrl-C. Hope you find time to verify the feature.
Thank You,
Zbigniew

**Comment by RedemptionC** [comment]
@zigm Yes,I just tried it,so glad to see that it supports copy short cut now,thank you!
