### ISSUE TITLE
Gmail labels

### ISSUE THREAD

**Issue by sardelich** [eneam/mboxviewer#22]
Support for gmail labels is highly welcome. However, in my case, I think they are not working ok. Especially, if possible, a label of sent emails would be great. There are some labels created but they dont reflect the state of gmail labels.

**Comment by zigm** [comment]
It is hard to resolve the issue without having access to the mbox file. However, you could perform small test to see whether the particular file contains "Sent" label. Perform the following steps:

start Windows Command window and change to the directory with the mbox file, for example

cd C:\test\mails

run the find command to search for lines containing Labels string. Make sure Labels string and file name are between quotes:

find "Labels" "All mail Including Spam and Trash.mbox"

You should see as below

X-Gmail-Labels: Inbox,Important,Opened,Category Personal
X-Gmail-Labels: Sent,Opened
X-Gmail-Labels: Inbox,Important,Opened,Category Personal
X-Gmail-Labels: Sent,Opened
X-Gmail-Labels: Inbox,Important,Opened,Category Personal
X-Gmail-Labels: Inbox,Important,Opened,Category Personal
X-Gmail-Labels: Inbox,Important,Opened,Category Updates
X-Gmail-Labels: Inbox,Important,Opened,Category Updates

You can run the following command to see lines with Sent string only

find "Labels" "All mail Including Spam and Trash.mbox" | find "Sent"

Let me what you see.

**Comment by zigm** [comment]
Another way is to view raw mail headers via Mbox Viewer

Select "View->View Raw Message Headers" and keep selecting mails and look for X-Gmail_Lables lines.

**Comment by zigm** [comment]
Hope you find time to help to diagnose the issue. If there is an issue with the current code I would like to address the reported issue in the next release so all users can benefit. In many cases I rely on users to report problems with MBox Viewer. Let me know whether you will be able to provide the information I suggested to collect in my last two posts. If you can provide any other information you can think that might help such as screen snapshots, it would be appreciated.

Thank You,
Zbigniew

**Comment by sardelich** [comment]
It seems that google takeout file was corrupted. Recreating and redownloading new one seems ok now.

**Comment by zigm** [comment]
Good to know you managed to resolve the issue. I am closing the issue. If you observe related issue, please reopen or create new issue.

Thanks,
Zbigniew
