### ISSUE TITLE
GMail Labels: thousands of "drafts" , "opened" and "catgory" labels where GMail has only one of each

### ISSUE THREAD

**Issue by nima-amin** [eneam/mboxviewer#24]
Is there a way to somehow eliminate the fact that mbox viewer creates an extra label for each and every single email that in the original GMail interface lie in the draft, opened and catogry labels? (And strange enough also for every single email that lies in one of my user-created labels while all other user created labels are teated like regular folders with several emails in them). The tree gets huge and cluttered this way when you have to scroll down literally thousands of labels.

**Comment by zigm** [comment]
That doesn't sound right and points to possible bug. In my testing using my downloaded gmail mail archive I don't see such issue. It is possible I am missing something that causes such an issue. Are you running the latest version v1.0.3.25 of MBox Viewer?  It is possible that older version of Mbox Viewer may have some issue with Gmail Labels.   I would have to investigate. Assuming you are running v1.0.3.25, can you delete existing Gmail Labels by right-click on a folder and selecting "Gmail Labels" -> Refresh.

**Comment by zigm** [comment]
Would you be able to attach snapshot of Labels created, obviously subset only. Thanks for your help.

**Comment by zigm** [comment]
I think I suspect what is happening. Mbox Viewer doesn't support certain characters in the label names and will replace some characters with the underscore. However, it looks like processing might be incorrect and can create separate label per email for the same original Gmail label. I will do more debugging, fix it and make a new release. Snapshot of a subset of labels from your setup will be helpful to confirm the problem.

**Comment by zigm** [comment]
I have created new v1.0.3.26 release of MBox Viewer to fix gmail label issue and to fix incorrect link to attachment in PDF mail document  issue. I hope the fix will address the issue you reported.  Hope you find time to verify the fix and provide feedback. Thanks for taking time to report the issue.

**Comment by nima-amin** [comment]
You might be right with your assumption, though. I use Gmail in German, and the labels in question are:

Entwürfe
Gröffnet
Kategorie__Soziale Medien
Kategorie__Angebote
Kategorie__Foren
Kategorie__Neugkeiten
Kategorie__Persönlich
Luís C. F. Henriques - musicologist

So, they either have German / Portuguese special characters or underscores, or both.

I used the 1.0.3.25 version.

How do I update?
![Entwuerfe](https://user-images.githubusercontent.com/75982635/154817053-fa316169-0c65-4625-88e4-49cfd53670de.png)
![Geoeffnet_Kategorie](https://user-images.githubusercontent.com/75982635/154817052-99f0df06-d7c4-4a19-8c2d-8ee0c512a072.png)
![Kategorie_Luis](https://user-images.githubusercontent.com/75982635/154817066-1d94bbb6-c0ec-45f9-968e-69812c916163.png)

**Comment by nima-amin** [comment]
How am I supposed to attach a screenshot here?

You might be right with your assumption, though. I use Gmail in German, and the labels in question are:

Entwürfe
Gröffnet
Kategorie__Soziale Medien
Kategorie__Angebote
Kategorie__Foren
Kategorie__Neugkeiten
Kategorie__Persönlich
Luís C. F. Henriques - musicologist

So, they either have German / Portuguese special characters or underscores, or both.

I used the 1.0.3.25 version.

How do I update?

**Comment by nima-amin** [comment]
You seem to have gotten it.

**Comment by zigm** [comment]
Sounds you managed to upgrade to v1.0.3.26.  You just download and install the new zip file and delete the old folder. There is no upgrade procedure.  Based on your last statement, you don't see separate label per email.  Unfortunately, the labels will look a bit funny since label names are limited to ASCII characters.  For the most part, MBox Viewer supports international characters but not in Labels.  MBox Viewer needs to be ported to UNICODE to provide full support for international languages.  It was initially develop as non UNICODE and now it requires non trivial effort to port to UNICODE.  I am planning to port the code to UNICODE in the future.

Thanks for your help in resolving the reported issue.  I hope the current version may work for you.

**Comment by zigm** [comment]
Closing the ticket. Please reopen if you see more issues.
