### ISSUE TITLE
Feature Request - Toggle to turn off grouping of conversations

### ISSUE THREAD

**Issue by OneYellowLemon** [eneam/mboxviewer#25]
A toggle to disable `group all related mails as conversations in the summary window` would be really useful.

**Comment by zigm** [comment]
Currently you left-click on the first column to group related mails as conversation and you left-clink on any other column, say Date column, to remove grouping. Sounds you are looking for a way to completely disable grouping. Sounds like the way it is currently supported may not obvious to users? or there is some other reason. Appreciate additional comments.

**Comment by OneYellowLemon** [comment]
Great, thank you. Obvious now that I know what i'm looking for, but yeah, I had trouble finding that before.

**Comment by zigm** [comment]
I agree grouping via left-click of the first column is not that obvious. Grouping is also supported via the right-click on a folder and selecting Sort By -> Conversations. I usually advice users to try the right and left click or double click on any item or empty screen area to learn what is possible and how it works by trying. You really can't do any damage by trying. You can always read the User Guide by that it is time consuming I admit. Hope that helps.

**Comment by OneYellowLemon** [comment]
Going to go ahead and close this, thank you!
