### ISSUE TITLE
linux build

### ISSUE THREAD

**Issue by Cyrix126** [eneam/mboxviewer#27]
Is there a way to compile the code to a Linux environment ?

**Comment by zigm** [comment]
Unfortunately MBox Viewer is strictly Windows code. Long time before I joined the project, there was a version based on WxWidgets. This version is no longer maintained and therefore you can compile MBox Viewer on Windows only.

**Comment by zigm** [comment]
I am closing this ticket since there is no plans to port MBox Viewer to Linux platform.

**Comment by K0-RR** [comment]
Hi @zigm, did something change in this regard?

**Comment by zigm** [comment]
Hi @K0-RR 

You can  check  #58 for additional context to your question.  I started to examine potential frameworks to port MBox Viewer to platforms other than Windows but I don't have much to report. Port requires very large effort and currently I am not able to commit large chuck of time to such effort. progress will be slow.
