### ISSUE TITLE
1.0.3.29 still shows 1.0.3.28 version number

### ISSUE THREAD

**Issue by voltagex** [eneam/mboxviewer#28]
![image](https://user-images.githubusercontent.com/83080728/171328027-efb98462-e415-4d55-9f3d-dbfdbcbf86d8.png)
![image](https://user-images.githubusercontent.com/83080728/171328087-05b7e7ea-7497-4122-8e07-29ce2aae6331.png)

**Comment by zigm** [comment]
Thanks, apparently I forgot to update the version.. Can't fix the version now, too much trouble. Will need to set the next version to 1.0.3.40.

**Comment by zigm** [comment]
Thanks for making me aware of the issue. I released v1.0.3.31 with all versions correct.
