### ISSUE TITLE
Trojan?

### ISSUE THREAD

**Issue by Girdauskas** [eneam/mboxviewer#33]
mboxview64.exe flagged this file as malicious

![image](https://user-images.githubusercontent.com/2959675/180425632-754b5664-144a-4417-a16b-9a35ae6b30ff.png)

**Comment by zigm** [comment]
Thanks for raising the issue.  This seems to be similar to the latest issue that was closed, see the closed issues.

If you have problem with Windows Defender, please run Windows Update to update the Windows Defender rules. Let me know if Windows Defender prevents you from running MBox Viewer.

Note also that the MBox Viewer package is scanned for malware by Sourceforge and no issues are reported.

**Comment by Girdauskas** [comment]
I used https://www.virustotal.com/ to check it. I noticed that only [1.0.3.32](https://github.com/eneam/mboxviewer/releases/tag/v1.0.3.32) version has this problem.
The previous version [1.0.3.31](https://github.com/eneam/mboxviewer/releases/tag/v1.0.3.31) has no problems so I am using that.

**Comment by zigm** [comment]
This is the false positive detection by some tools. Great majority of tools didn't complain.  The issue was reported  also here

https://github.com/eneam/mboxviewer/issues/32

Not exactly sure  why this tools report an issue. Obviously v1.0.3.32 has some new code which will be present in future releases.

**Comment by zigm** [comment]
In general if 55 tools report no malware, you can assume software is safe. Note that software downloaded from Sourceforge is scanned by BitDefender and no risk is reported, BitDefender in the report by virustotal.com you provided flags Variant.Lazy warning which seems to be ignored by Sourceforge scan, likely as not important.

**Comment by Girdauskas** [comment]
Zero detections are safe :)

**Comment by zigm** [comment]
Zero  detection is safe(er) -:) and not necessarily safe.   But not all tools have up to date rules as the latest case with Microsoft Defender illustrates.  After the scan Microsoft Security decided that package is safe and updated the rules.

**Comment by zigm** [comment]
Windows Defender no longer reports false detection. BitDefender utilized by Sourceforge never reported any issues.
