### ISSUE TITLE
Allow customization of the from email address when forwarding emails

### ISSUE THREAD

**Issue by JoeMarkov** [eneam/mboxviewer#37]
My SMTP Server does not use an email as the login, instead, I have a username like joe12345, and when I try to send it, it complains that the from email is invalid.

So, I wish there was a way to provide the FROM email/name when forwarding an email from your awesome application. This should be separate from the custom SMTP login name.

**Comment by zigm** [comment]
The joe12345 user account name should work. Select File->SMTP Mail Server Config and set User Account and Password. Follow by Save and Close.  That should create SMTTP.ini file in C:\Users\UserName\AppData\Local\MBoxViewer\MailService directory.

Let me know if that helps or it doesn't work.

![image](https://user-images.githubusercontent.com/36137255/200190530-6c1adcc6-2c30-45d8-a31e-62ea4c49dbc8.png)

**Comment by zigm** [comment]
I did reread your message and it appears that  MBox Vierwer could allow to configure separate FROM name and separate SMPT login name for Custom SMPT configuration. That makes sense and will enhance MBox Viewer after I am back from my trip.

What about Password. Sounds that in your case single password will work. Do we need two separate passwords for general case?

**Comment by zigm** [comment]
Separate Passwords don't make sense -:)

**Comment by JoeMarkov** [comment]
I was using the custom SMTP config option and a single password field is fine, just separating the FROM email from the username is perfect! 

thanks!

**Comment by zigm** [comment]
I am finally back from long vacations and released v1.0.3.36 to support your request. I did the basic functionality test but I don't have ability to test the scenario you described. Appreciate if you test the separate login and FROM names case and let me know if it works. I should probably ask you to test the prototype before I made the official release. Hope the released version works.

**Comment by JoeMarkov** [comment]
I tried v1.0.3.36 and it works, I managed to forward email to my custom SMTP server. Thanks! :-)
