### ISSUE TITLE
Feature request - export email addresses

### ISSUE THREAD

**Issue by gszakacs** [eneam/mboxviewer#43]
Hi,
I would like to request an email address print/export feature. 
Desired operation: select emails, right click, export/print all email addresses from to/cc/bcc/from/email body into separate, preferably csv file.
Thanks

**Comment by zigm** [comment]
MBox Viewer supports "Print to CSV" option to create CSV file with the selected mail header fields, attachment names and mail text. Select mails (use the standard Windows approach) , right click on the selected mails and select "Print selected mails to --> CSV" . Dialog will be shown to select data to export to CSV.

Let me know if that works for you.

**Comment by gszakacs** [comment]
Thanks for the tip, your suggestion worked great ! Thanks for the app, it is faster and better at exporting contacts from a mbox file than other solutions I tried.
