### ISSUE TITLE
Convert to HTML

### ISSUE THREAD

**Issue by misaligar** [eneam/mboxviewer#45]
Is there a way to convert the `mbox` file into separate `html` files for each email?

**Comment by zigm** [comment]
MBox Viewer supports printing selected mails to separate HTML files. Select "File-->Print Config" and set "Print selected mails to separate files --> HTML" . Select subset or all (CTRL A) mails, right click on any of the selected mails  and select "Print Select Mails to --> HTML". When done dialog will be shown and select "Open File Location".

Note that created HTML files are not just raw Mail message but HTML files contain Mail Header Fields, plus Mail message plus some text formatting.  Print Config dialog allows you also to configure the file name template.

**Comment by misaligar** [comment]
@zigm Thank you so much! Exactly what I was looking for.
