### ISSUE TITLE
[FR] manually remove emails

### ISSUE THREAD

**Issue by eadmaster** [eneam/mboxviewer#46]
Allow to delete a group of manually-selected emails via the context menu.

**Comment by zigm** [comment]
Current MBox Viewer allows users to delete selected emails but only when emails are placed on  "User Selected Mails" list.
When mbox file is opened, all emails are placed on "All Mails" list. Right click on any email and select "Copy All into User Selected Mails" option. Next, select "User Selected Mails" list.  Select emails, right click on one of the selected mails and select "Remove Selected Mails" option.  Next, you can select "Save All as MBox Mail Archive file" option to create new archive and open by MBox Viewer.

MBox Viewer doesn't support removal of mails from the original mbox file.  Once you are comfortable, you can delete original mbox file and keep the new mbox file.
