### ISSUE TITLE
program crashes while opening mbox file

### ISSUE THREAD

**Issue by mbcbus** [eneam/mboxviewer#5]
Windows server 2016 (only windows machine I have access to)
dual core processor 8gb RAM
mbox file downloaded from gmail, approx 4.2gb in size.

When trying to open the file, the program crashes with the following error:
<img width="664" alt="Screen Shot 2020-02-13 at 7 43 56 AM" src="https://user-images.githubusercontent.com/20741877/74436735-ed9d5b00-4e34-11ea-8e45-ee4bc6d1335f.png">

Originally I thought it was because the program was running off C:/ and my data file was on my D:/ drive. I moved the data file to the C:/ drive and the program still crashed (but ran a little longer before crashing?)

When restarting the program, this error message pops up from windows as well:
<img width="415" alt="Screen Shot 2020-02-13 at 7 42 48 AM" src="https://user-images.githubusercontent.com/20741877/74436816-14f42800-4e35-11ea-92e0-af8a6e2f326b.png">

Any suggestions on what to try, or how I can verbosely log errors to help? I am seeing the following error in the windows event viewer:
<img width="437" alt="Screen Shot 2020-02-13 at 7 49 12 AM" src="https://user-images.githubusercontent.com/20741877/74436998-63a1c200-4e35-11ea-9f51-e4db8d8be52b.png">
`mboxview.exe 
   1.0.3.6 
   5e13fd56 
   mboxview.exe 
   1.0.3.6 
   5e13fd56 
   c0000005 
   00006bf2 
   1520 
   01d5e26a34c04c15 
   C:\Users\Administrator\Downloads\mbox-viewer.exe-v1.0.3.6\mboxview.exe 
   C:\Users\Administrator\Downloads\mbox-viewer.exe-v1.0.3.6\mboxview.exe 
   ab8360d8-896e-44e6-b707-2a128e456066 
`

**Comment by mbcbus** [comment]
It appears this may be a timestamp issue similar to:
https://github.com/eneam/mboxviewer/issues/3

I will see if I can play with settings as well as test with an older release to see if anything else works.

**Comment by mbcbus** [comment]
I was able to open the file with version 1.0.2.8. I'm not sure how to troubleshoot it further.

**Comment by zigm** [comment]
Hi,

Thanks for reporting the issue. It is likely you are seeing the issue
already reported on Sourceforge by Carlos.
He was able to run v1.0.3.5 without problem. Did you try v1.0.3.5 ?

10 days ago I posted the test version of mbox viewer on my test project on
github and sourceforge.  Carlos was going to verify the fix before I
release the official package.

Are you willing to verify whether the fix works for you ? See below the
instructions below. The ticket is on the sourceforge is:

https://sourceforge.net/p/mbox-viewer/discussion/516066/thread/53c7faa848/?limit=25#4adc/2f0b/0162/477d/d61a/08a3

The test version is posted on:

https://github.com/zigm/hello-world/releases
https://sourceforge.net/projects/hello-git-world/files/1.1-test/

The issue you may face, which I don't fully understand, is that Window
Defender may complain about the the same program downloaded from the my
test project but not from the mbox viewer project.

You may need to allow Defender to to run the test program.  Let me know if
the test version resolves the issue you reported and will create official
release.

Cheers,
Zbigniew
------------
Hi Carlos,

I have new versions of mbox viewer and hope you find time to test.  You can
download two new packages :

mbox-viewer.exe-v1.0.3.7-fixed.zip
mbox-viewer.exe-v1.0.3.7-not-fixed.zip

from

https://sourceforge.net/projects/hello-git-world/files/1.1-test/

You may want to read the HELP.txt file for  helpfull information.

Please run first the mboxview executable from

mbox-viewer.exe-v1.0.3.7-not-fixed\DEBUG  directory.

Hopefully the mboxview will crash and generate files as described in the
HELP.txt. Please attach these files to the ticket. You may need to select
Refresh Index File option to restart parsing.

Next run he mboxview executable from

mbox-viewer.exe-v1.0.3.7-fixed\DEBUG  directory.

Hopefully you wil see no crash.

NOTE: In the past I did see cases when Windows Defender blocked
mboxview.exe from running when downloaded from my Hello-world test project
on Sourceforge. The same files downloded from the mbox viewer site work
fine.  Please click the button to allow the new mboxview to run, it is no
different than one from the mbox viewer site.

Thank you,
Zbigniew

**Comment by zigm** [comment]
Hi,

I created new v1.0.3.7 release with unverfied fix to parsing issue you reported. 

Hope you find time to verify the fix. There are few additional enhancments in v10.3.7.

Thank you for your time and effort.
Zbigniew

**Comment by zigm** [comment]
The latest release resolved similar complains from other users so I assume issue is resolved unless the ticket creator objects.
