### ISSUE TITLE
Print to pdf with header and footer

### ISSUE THREAD

**Issue by igiuseppem** [eneam/mboxviewer#53]
Hello.
When you use the "print to" menu to print a mail in pdf format, you will obtain a pdf with date and time in the header and the full path in the footer, even though the option "Header and footer" in the "Print Config" is disabled.

Looking forward to hearing you
Kind regards
Giuseppe

**Comment by zigm** [comment]
Hi Giuseppe,

Unfortunately Chromium introduced new command line flag to suppress header and footer in print to PDF. It looks like Edge Browser understand old command line option and the Chrome Browser doesn't. It looks like you configured Chrome Browser for printing. 

I tested that there seems to be no harm to specify old and new command line options at the same time to resolve the issue you raised. I am working on new release which I hope will be completed soon. It should resolve the issue. Please try to configure Edge Browser for printing and let me know if that resolve the issue.

Respectfully,
Zbigniew

**Comment by zigm** [comment]
Hi Giuseppe,

I spoke too soon. I just updated my Edge to the latest version and I see Edge has now the same issue.  Unfortunately new release is required to resolve the issue. I will let you know when new release is ready.

Respectfully,
Zbigniew

**Comment by zigm** [comment]
I just remember that there is work around the issue if you are interested. By default, MBox Viewer executes Edge or Chrome directly to print to pdf. However, Edge or Chrome can be called indirectly via provided script scripts/HTML2PDF-single-chrome.cmd in the package.  The HTML2PDF-single-chrome.cmd has to be updated as follow (change is in bold):

call "%CmdPath%"  --headless --disable-gpu **--no-pdf-header-footer** --print-to-pdf="%PDFdir%\%HTMLNameBase%.pdf" "%HTMLFilePath%"

You also need to update Print Config dialog as below. By default HTML2PDF-single-wkhtmltopdf.cmd is configured. You need to update the script name to HTML2PDF-single-chrome.cmd or HTML2PDF-single-edge.cmd

I attached updated scripts in case you would like to try until new release is available.


![image](https://github.com/eneam/mboxviewer/assets/36137255/e7675206-86c5-467e-af84-7a5381bb06ea)

[HTML2PDF-single-chrome.cmd.txt](https://github.com/eneam/mboxviewer/files/13932889/HTML2PDF-single-chrome.cmd.txt)
[HTML2PDF-single-edge.cmd.txt](https://github.com/eneam/mboxviewer/files/13932890/HTML2PDF-single-edge.cmd.txt)

**Comment by zigm** [comment]
New release v1.0.3.41 resolves the issue you reported.

**Comment by igiuseppem** [comment]
> New release v1.0.3.41 resolves the issue you reported.

Thank you for your help and your answer!
