### ISSUE TITLE
Spam Mailadress and Domainfilter

### ISSUE THREAD

**Issue by vosslera** [eneam/mboxviewer#55]
Hi,

would nice is there a Spamfilter for spezific mailadresses ```spam@domain.com``` and ```@maildomain```,
on the other side, a Whitefilter for good and Trustable Mailadresses, like ```@yahoo.com``` or ```frend@yahoo.com```

so, if there in trusted maildomain like yahoo.com, but a mailadress like ```spam@yahoo.com```
is sorted out and let see under "spammails" (so a extra tab for spam/blacklisted mails for looking on before reload and deljob of the blacklisted mailadresses and bad domains ...

the 3rd idea, a  connection to Carddav on Own/Next Cloud for 
have also a listing source vor Whitelisting known Mailadtresses.

if comes a White and Blacklising filtering would it nice to have..
and a connection to an own carddav for carddavwhitelist would more great ..

best

**Comment by zigm** [comment]
Hi,

You need to help me what we are trying to achieve here. First lets agree that MBox Viewer is not full mail client such as Gmail. It will read mail archive files, parse and present all mails to users.  How would you use a Spamfilter on archive mails? Or you have something else in mind. Please elaborate a bit more.

Thanks,
Zbigniew

**Comment by vosslera** [comment]
is is only a reader for MBox-Files ?
>A simple viewer to view mbox files such as Thunderbird Archives, Google mail archives or simple Eml files.

oh, okey, your programm looks like "Pop Peeper the "MailBox" checker from Esumsoft with antispam, but ist is commercial..

if your Proggy not a Mailboxchecker over imap/pop or something be i wrong and you can close this issue :)

best

**Comment by zigm** [comment]
MBox Viewer connects only to SMTP Mail Servers to forward mails from archive mail files. It doesn't connect to IMAP Mail Servers.  I will close the issue.

**Comment by vosslera** [comment]
Hi @zigm  :)

well SMTP, there could be between connecting, mail-reading and clousing, a Spamfilter by checking the Mailadresses and "from" (sometimes other possibilitys.. by ip a.E.) & Tags in the mail, like "potent","sex" and so on typed in by the Programmuser.. there with is there a possibility for filtering by check the mails
and marking for deleting by the next seek on mailserver ...

well, so it is , if connect over SMTP a mailserver, can at this point check not only the mails, also filtering and trashmarked, and deleting by the next connect unwanted mails by different tags..

best regards
Blacky

**Comment by zigm** [comment]
Hi Blacky,

Sorry but it not clear to me what we try to achieve. MBox Viewer doesn't connect and doesn't retrieve mails from IMAP mail server.  Application needs to be trusted application to to connect to IMAP mail server.  In case of Gmail, it is long process to certify application as trusted by Google. And there are other challenges. Also, more dynamic database than currently supported by MBox Viewer is required to support mail retrieval. I have no plans to support IMAP mail servers.

Could MBox Viewer monitor text created by users? I guess it could but MBox Viewer is basically for single users and I don't see a need for a user to monitor himself. I might be missing something.

Thanks

**Comment by vosslera** [comment]
@zigm :+1:
