### ISSUE TITLE
Keyboard navigation shortcuts?

### ISSUE THREAD

**Issue by cjholly** [eneam/mboxviewer#61]
I am not seeing any keyboard shortcuts listed in Help. It would be nice to be able to switch between the email message pane and the header pane if it were easy to code and would not mess up the refreshing simplicity of the program (more like the way I am using it so far is simple!)

**Comment by zigm** [comment]
Hi @cjholly 

Thank you for raising potential enhancement.  I would like to understand better the potential feature.  Please comment on the header pane in your description. Do you refer to the raw header pane that is displayed by the right click on the header part in the message pane and selecting "View raw message header" option ?

Also **"I am not seeing any keyboard shortcuts listed in Help."** 

Do you refer to the Help option in the top menu that supports "Mbox Help", "About mboxview", "user Guide", etc sub-options ?

**Comment by cjholly** [comment]
I'm not sure how to answer your questions. So I will give you an example of what I do

I have a link that runs mboxviewer on a specific folder in like this:

"C:\MboxViewer\mboxview64.exe" -MAIL_FILE="C:\Users\OGreatOne\AppData\Roaming\Thunderbird\Profiles\r79mwpdr.default\Mail\Local Folders\Cases.sbd\Palooka, Joseph Q"

What I see when that opens is 2 panes (I've hidden the tree). The one on the left shows the the usual date, subject, sender, recipient etc. The one on the left shows the email message content. 

Usually I keep my cursor in the left pane and just arrow up and down as needed. Sometimes the message is longer, than can be displayed, so I have to click that pane and arrow down to see. Then I have to click back in the left pane to go to another message. 

I have a perhaps unhealthy relationship with my keyboard. I can't keep my hands off it. So it is very disruptive to have to reach for the mouse. I probably need a support group. Oh, yeah, and I do not want a touch screen either. One of those. . . .

**Comment by zigm** [comment]
Thanks for clarification. I will investigate how to find the "next?" pane and set the focus. Not sure whether there are  standard shortcuts to change the focus. I will provide an update.

MBox Viewer supports few shortcuts but they are not listed in a single place. Will try to address the issue.

**Comment by zigm** [comment]
I have working solution. I use CTRL+n to cycle through Message and Mail Summary (or mail headers) panes. I suppose standard shortcut is ALT+TAB ? I am not super efficient with keyboard so CTRL+n works for me better (requires two hands -:)).

In the current solution there is no indication which window is active.

Please comment.

**Comment by cjholly** [comment]
zigm, I don't see why that would not work fine. Actually I think Alt-Tab is going to switch between open windows. It won't stay in mboxviewer. It would open a different window entirely. I think Ctrl-Tab sometimes works to switch between panes, but I think Ctrl-N would be OK. How do I try it? If you are saying it is already available, nothing happens when I try it.

**Comment by zigm** [comment]
@cjholly . I have created new release v1.0.3.42 to enable cycling through Message and Mail Summary. Also, you should be able to minimize/restore MBox Viewer window and/or play with other application without loosing state/focus.

Let me know if new release works for you.

**Comment by zigm** [comment]
No feedback received, closing.
