### ISSUE TITLE
New feature request - Theme options

### ISSUE THREAD

**Issue by halyuruk** [eneam/mboxviewer#7]
It would be great to have an option to create a user defined theme or to select a theme from the list of pre-defined themes just like in notepad++ or to have at least a dark theme.

White backgrounds of the left selection pane, mail list pane and message reading pane are very bright.

Thanks.

**Comment by zigm** [comment]
I will investigate the request and provide an update. Changing a theme in
the message reading pane may not work as expected except for the plain text
messages.

**Comment by zigm** [comment]
I did prototype support for the color customization and will integrate into
official release. It will take some time however. I will provide an update
on progress.

**Comment by zigm** [comment]
I created v1.0.3.9 to support custom color styles. Appreciate if you find time to evaluate this new feature and provide feedback.

Cheers,
Zbigniew

**Comment by halyuruk** [comment]
Thank you very much for making pre-defined and custom color configuration options available in this update.
Definitely saves eyes compared to white background.

**Comment by zigm** [comment]
Thanks for the feedback. Hope feature will be helpful to more users. Feel
free to raise requests for enhancements. No guarantee it will be
implemented -:) but I will review and evaluate if the request is doable
given the framework used by the mbox viewer.

**Comment by zigm** [comment]
Closing the ticket.
